### ISSUE TITLE
Official title of all npm published packages

### ISSUE THREAD

**Issue by AlexMoroz** [Rostlab/JS16_ProjectE#10]
From now `got*` is gonna be the official title of all npm published packages.

https://github.com/Rostlab/JS16_ProjectC_Group10/issues/116#issuecomment-197052457

Notifications:
@TheZoker @CavidSalahov @jonny3576 @AngeKouemo @Emiliyana

**Comment by jcebel** [comment]
How do we differ between project D4 and D5?
gotsentiment4 sounds like it would be Version 4...
Any suggestions?

Same question belongs to project B

**Comment by AlexMoroz** [comment]
@nicoladesocio and @subburamr 
Do you use different ML technics? 
What's unique in your projects?

@julienschmidt and @Logarythms 
What's unique in your projects?

Lets have fancy name brainstorming here)

**Comment by kajo404** [comment]
Group 5 here, unique about our project is that it is very basic and we analyze on a daily basis.
my Ideas so far: gotdailysentiment gotEZsentiment

**Comment by jcebel** [comment]
Ok I'll use gotdailysentiment for ProjectD5, if no one is stating any complaints :)

**Comment by subburamr** [comment]
For group 7 and our project, the difference would just be the dataset we use and SVM parameters we select in Weka. You could use [gotPLOD](https://github.com/Rostlab/JS16_ProjectB_Group6/issues/29#issuecomment-197908828) for group 6

**Comment by AlexMoroz** [comment]
only small letters, if group 6 will have `gotplod`, so what will be the name for group 7?

**Comment by julienschmidt** [comment]
I'd propose got-sentimental for Group 4

**Comment by sacdallago** [comment]
No `-` @julienschmidt,
for the Rest: ok

**Comment by sacdallago** [comment]
Can this be closed?
