### ISSUE TITLE
Data storage

### ISSUE THREAD

**Issue by AlexMoroz** [Rostlab/JS16_ProjectE#11]
@sacdallago I have a question.

The project B are going to store the results in the database, according to this https://github.com/Rostlab/JS16_ProjectB_Group7/issues/7.

Does it mean that they don't need package any more?
Project F can just use the results from database via API.

**Comment by sacdallago** [comment]
Good observation. On the other hand: what if you want to rebuild the database? How do you get the PLODS?

So I think they still need to provide a function to get the PLODS and this still needs to become a package that might be integrated in **A** to regenerate the data, should this (and it will be) necessary.

Just to give you a preview of what will happen on April 10:

I will clone repo A + F, run the instructions on how to generate the data and set up the project on an empty database, and that's gonna be it. :D hope this helps with planing :)

**Comment by AlexMoroz** [comment]
@sacdallago 

> might be integrated in A

Might be, or have to be?
If we need to integrate it to **A** we need to specify mongo config, if to **F** we need to add api config?
I think it's important to know now :)

**Comment by AlexMoroz** [comment]
@TheZoker @CavidSalahov @jonny3576 @AngeKouemo @Emiliyana

So from now:
Project D will be integrated to F and Project B to A.
