### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectE#13]
Yellou guys, I just wanna check something:
- https://github.com/Rostlab/JS16_ProjectB_Group7/issues/12
- https://github.com/Rostlab/JS16_ProjectC_Group10/issues/161
- https://github.com/Rostlab/JS16_ProjectF/issues/52
- https://github.com/Rostlab/JS16_ProjectB_Group6/issues/50

is not something you may want to gitignore, right?

**Comment by jcebel** [comment]
I do not get the point... Sorry. Could you explain it?

**Comment by yashha** [comment]
https://devcenter.heroku.com/articles/config-vars

**Comment by yashha** [comment]
https://developer.github.com/guides/managing-deploy-keys/

**Comment by AlexMoroz** [comment]
@sacdallago 
we can't gitignore travis configuration file)
can we do this file private? or do you have any suggestions?

**Comment by AlexMoroz** [comment]
@sacdallago 
It's actually encrypted, less also shows their keys https://github.com/less/less.js/blob/master/.travis.yml#L17.
I think encryption include also the repository name because it is not the same for different repos.
So you can get the key, but you can publish only from this repository.
I think you can close all issues=)

**Comment by AlexMoroz** [comment]
@sacdallago 

> npm ERR! publish Failed PUT 401
> npm ERR! Linux 3.13.0-40-generic
> npm ERR! argv "/home/travis/.nvm/versions/node/v5.8.0/bin/node" "/home/travis/.nvm/versions/node/v5.8.0/bin/npm" "publish"
> npm ERR! node v5.8.0
> npm ERR! npm  v3.7.3
> npm ERR! code E401
> npm ERR! You must be logged in to publish packages : gotmap
> npm ERR! 
> npm ERR! If you need help, you may report this error at:
> npm ERR!     https://github.com/npm/npm/issues
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/travis/build/Rostlab/JS16_ProjectC_Group10/npm-debug.log

see, that guys are not so stupid :)
https://github.com/Rostlab/JS16_ProjectC_Group10/commit/ca3b81a7c54babff961d9d4a3e6aa404e1616262

**Comment by sacdallago** [comment]
Thanks! I was thinking something like this would be the case, that's why I asked and why the title was "semantics" :D they shouldn't probably call it "secure"
