### ISSUE TITLE
Update data via API vs update data via MediaWiki

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectE#14]
(Sorry **E** if I use your space but this was where it made more sense to me)

Everyone @Rostlab/js_cs_sose_2016_students :
There is a discussion going on [here](https://github.com/Rostlab/JS16_ProjectA/issues/81#issuecomment-198773569) about _**where**_ scraped data (!!! ONLY) needs to be updated. The options are:
1. Via API.
2. Via MediaWiki + running the scrapers again.

The implications are respectively: 
1. The API opens for POST requests to directly manipulate **scraped** data.
2. The API doesn't allow modifying **scraped** data.

I'm all in for number 2 for the following reasons:
- People cloning A's repo want to have the same data as their friends who cloned the repo 2 months earlier
- Updating the data via GUI is the preferred method for normal human beings
- Databases can easily be rebuilt and updated by re-scraping the data off the wiki, without worrying about  concurrency (someone updated the data via API call, now someone else wants to update the data via re-scraping... What is right?)
- A routine can be set up that will update the database periodically by re-scraping the data.  

If you are against implementing option 2 please comment here within 2 days, otherwise I take it as everyone knows what's going on and is fine with that.

**Comment by sacdallago** [comment]
@kordianbruck @Adiolis OK. So it's final:

Updates to scraped data only via update of wikis. / Close POST calls for modifications on the scraped data

**Comment by kordianbruck** [comment]
Why are you closing this @sacdallago  - did you remove the already existing update methods from the api?

**Comment by kordianbruck** [comment]
Ah, wupps, this is in Project E, not A...
