### ISSUE TITLE
Missing settings link on code climate

### ISSUE THREAD

**Issue by TheZoker** [Rostlab/JS16_ProjectE#15]
I'm currently setting up code climate for [Project A](https://codeclimate.com/github/Rostlab/JS16_ProjectA) and [Project F](https://codeclimate.com/github/Rostlab/JS16_ProjectF).

Now I want to link it to travis. Therefore I need the code climate token which is generated in the settings.
But the settings do not show up for me. I found [this wiki entry](https://docs.codeclimate.com/docs/missing-settings-link), which tells reasons, why it's not shown.

Can you help me find the reason?
Is it a lack of permissions?

@sacdallago

**Comment by sacdallago** [comment]
?? I don't know where you get that screenshot from, but I usually go into the settings from the repo itself, top-right corner.
Live screenshot attached :D

![screen shot 2016-03-21 at 10 19 16 am](https://cloud.githubusercontent.com/assets/6240943/13914401/796d9e5a-ef4e-11e5-8a8e-e8d77a5bc908.png)

You have write access to the repos, which is as much as I can give you without becoming admin/owner.

If you still can't solve the problem, we have to think of a way that doesn't involve giving you god mode :)

**Comment by TheZoker** [comment]
It's not about the github settings, but about the code climate settings :) 

Maybe a way would be, that one of you (tutors) go to code climate, connect it to github and get the token for both repositories. 
Then you can send me the token and I can include it in the Travis config file. 
More infos on the wiki link above. 

Will that work for you?

**Comment by sacdallago** [comment]
'course. Send me an email, I'll answer with the tokens

**Comment by sacdallago** [comment]
I stand corrected. I can access the settings but I cannot access the org on code climate? This is the weirdest shit ever.

**Comment by sacdallago** [comment]
@TheZoker 
I'm in the settings page but I can't find this _token_ anywhere :D
![screen shot 2016-03-21 at 4 41 19 pm](https://cloud.githubusercontent.com/assets/6240943/13924259/eb05e830-ef83-11e5-8eca-8b7f10ba617f.png)

and 

![screen shot 2016-03-21 at 4 42 55 pm](https://cloud.githubusercontent.com/assets/6240943/13924291/0c4533b6-ef84-11e5-898f-89913f8a3f9a.png)

Maybe you want the _Analysis configuration file_?

![screen shot 2016-03-21 at 4 44 06 pm](https://cloud.githubusercontent.com/assets/6240943/13924328/2a6ad0bc-ef84-11e5-8faf-5cc938d87659.png)

**Comment by TheZoker** [comment]
Thank you for your effort!

As written [here](https://www.npmjs.com/package/codeclimate-test-reporter), this should be the solution:

> The CODECLIMATE_REPO_TOKEN value is provided after you add your repo to your Code Climate account by clicking on "Setup Test Coverage" on the right hand side of your feed.

**Comment by TheZoker** [comment]
@sacdallago Any news on this?

**Comment by sacdallago** [comment]
Hey. I was away yesterday and I still haven't any clue of where that damn _Setup Test Coverage_ is. Are you around in uni by any chance?

**Comment by TheZoker** [comment]
Yes I'm arround in the Uni today at 16 o'clock. But I'm not having a notebook with me. Is that a problem?

**Comment by sacdallago** [comment]
no. Come to rostlab please 1.9.58 asap

**Comment by TheZoker** [comment]
Sry had to leave earlier. Are you there tomorrow?

**Comment by sacdallago** [comment]
Not planning to go :D let's call!

EDIT: tomorrow. Like, sometime

**Comment by TheZoker** [comment]
When are you in the Uni today? 

Have a look here: https://docs.codeclimate.com/docs/setting-up-test-coverage

> Important: If you are running your tests via a CI service that we've directly integrated with (Semaphore, Solano Labs, and Travis CI), scroll to the bottom of your repository's Test Coverage tab, and select your CI. Perform the steps listed on the page.

**Comment by sacdallago** [comment]
@TheZoker I'm not going, I need to get ready to go home. Can you please skype/hangouts/facetime/whatever before 12? Write me an email please, I receive updates there quicker

**Comment by sacdallago** [comment]
We did this, didn't we @TheZoker ?
