### ISSUE TITLE
Endpoints!!!!!!!!!!

### ISSUE THREAD

**Issue by sacdallago** [Rostlab/JS16_ProjectE#16]
Guys, please pay attention that NO-ONE uses static endpoints in their code.
At this stage stumbling upon already two repos that have a static route to bruck's server is unacceptable:
- https://github.com/Rostlab/JS16_ProjectB_Group6/blob/b0b138d72c513fca2526b7a3d31b2f8914fc7867/api-handler/dataAccess.js#L11
- https://github.com/Rostlab/JS16_ProjectD_Group5/blob/2a48bb68d63f4b3214e7b0c063bfb9dc254bdc8d/db/dbA.js#L36

This is definetly, definetly your responsability :D So pay close attention to these things!!! As well as not-having database configuration options in the package init for some of the projects! **careful!**

Bruck's gonna tier down his server at some stage because I want to test if the packages are able to stand on their own feet.

**C10** did an excellent job in making their module... modular! https://github.com/Rostlab/JS16_ProjectC_Group10/wiki/Init-New-GoT-Map-and-Options

**Comment by jcebel** [comment]
Do You mean it is Bad to have database-config-option in the package-init- or is it a good thing to have that?
I'm a little confused because I thought that would be a good thing to have this?

**Comment by sacdallago** [comment]
No. I'm exactly trying to stress out the point that everything needs to be configureable!

**EDIT**: The first link on my previous post is already pointing on something that has been changed because of my remark, the second link still shows you what is not good, aka: hard coded endpoints **AND** database configurations

**Comment by sacdallago** [comment]
Hey guys. How are we doing on this? Everything under control?

**Comment by sacdallago** [comment]
Again. Is everything checked and set?

**Comment by jcebel** [comment]
It gets checked at the moment.. But it should be set

**Comment by jsalahov** [comment]
As all projects got integrated without problem, I think it is ok to close this
