### ISSUE TITLE
Integration of D5

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectE#17]
@jonny3576 
We have a problem, at the moment our app is fully running in the client, so if we want to integrate the sentiments analysis api, we have to handle the sensitive information needed for the config.
So we have two options:
- make an own api which serves your information
- you make it that we don't need passwords
- A implements your functionalities, or the most important ones (would be more convenient for us)

Do you have other suggestions?

**Comment by jcebel** [comment]
Hey I will come back to this as soon as possible. I will have a discussion with the guys from D5 a 2 am.

**Comment by jcebel** [comment]
@yashha and I just discovered the main problem, that they have no server-side logic till now and the whole Project F runs on the Client machine, but in D5 is some functionality of automated analyses, which needs to be serverside.
We discovered the problems but still need to figure out how to handle them... 

@yashha likes the idea most that A implements the functionality. But we both do agree, that it is a bad solution to change the whole structure of the project. 

So we need to find a better solution. If someone has additional ideas please share them with us! 
Project D5: @kajo404 @Logarythms @vanp33 

Maybe @CavidSalahov has a suggestion as he will integrate Project D4?

PS: The automated function starts automatically, when the credentials for A-API access and Twitter-API are passed as configuration. see [index.js](https://github.com/Rostlab/JS16_ProjectD_Group5/blob/develop/index.js) line 8

**Comment by jsalahov** [comment]
I would go with @yashha's first suggestion. Why not initialize D5 in your [server.js](https://github.com/Rostlab/JS16_ProjectF/blob/develop/server.js) and set-up additional routes for it?

**Comment by jcebel** [comment]
@kajo404 had the same opinion. Sounds that doable to you guys? 
@sacdallago any suggestions?

**Comment by yashha** [comment]
Yea sure, I think it will work.

**Comment by yashha** [comment]
I like the way the cavid wanna do this, can you also do it like this jonas or have you other things to do and we should implement it?
https://www.npmjs.com/package/gotsentimental

**Comment by jcebel** [comment]
you mean to set up the confiq manually or that there exists to entrypoints?
Ah got it :) We will work on it

**Comment by yashha** [comment]
I meant, that he has already done a node instance, which we just have to start. ;)
`node app`

**Comment by sacdallago** [comment]
Sorry guys, I was away for the day and am still traveling:

I get the problematic aspects, I was thinking you gouys (F) could couple a backend to your frontend, but setting up an API with just these dummy routes OS an acceptable solution.

**Comment by jcebel** [comment]
Ok I think I get it. And I will work on it. Tomorrow 12:00 is my personal deadline for this

**Comment by sacdallago** [comment]
Merci

**Comment by yashha** [comment]
Well we can couple it, everything is possible. 
But thanks jonas :heart:

**Comment by jcebel** [comment]
As I can't reach @yashha at the moment (No problem a man needs its sleep ;-) ), I will leave my thoughts for open discussion: I had some talking with @CavidSalahov and we both do agree, that it is indeed conveniant for Project F, what Project D5 did, but they were going down this road very early in the project. But Project D5 did not. This is not a complaint, it's just the way it is at the moment. It would need time and effort to change the whole setup of the Project, which is needed at other places right now (Deadlines and stuff). I don't like the idea and the way how they need to change the architecture again.

Correct me if I'm wrong, but as I've seen Project F got a small backend/serverside application [here](https://github.com/Rostlab/JS16_ProjectF/blob/develop/server.js)? 

So I would suggest we go down the route, which @CavidSalahov and @sacdallago suggested and Project F needs to do the frontend-backend-coupling-thing. (Hope this phrase is understandable?)

This is my opinion. Please respond to that if you feel unhappy about it or agree.

**Comment by yashha** [comment]
So we make it too our task, before we loose more time.
I think it can be done in a day.
