### ISSUE TITLE
How to include your components?

### ISSUE THREAD

**Issue by yashha** [Rostlab/JS16_ProjectE#4]
Do you already know how we are going to include your components?

**Quote from google groups:**

> make sure that team F knows how to add this modules to web site

Greets
Yasar :)

**Comment by jsalahov** [comment]
Just use npm install as usual, but instead of package name write github url in following form:
**githubname/githubrepo#branch**

Rename the placeholders, for further details see [here](https://docs.npmjs.com/cli/install)

**Comment by yashha** [comment]
Thanks

**Comment by sacdallago** [comment]
I like to see how you entered the project @CavidSalahov Keep on going!
