### ISSUE TITLE
Deploying NPM with TravisCI

### ISSUE THREAD

**Issue by kordianbruck** [Rostlab/JS16_ProjectE#5]
https://docs.travis-ci.com/user/deployment/npm/

should be easy :)

**Comment by AlexMoroz** [comment]
Small notification:
@TheZoker @CavidSalahov @jonny3576 @AngeKouemo @Emiliyana 

If you have problems with it ask here, I will answer.

https://docs.npmjs.com/getting-started/publishing-npm-packages
https://github.com/travis-ci/travis.rb

**Comment by sacdallago** [comment]
Can this be closed?

**Comment by jcebel** [comment]
From my site :) I think everything is published to npm isn't it?
