### ISSUE TITLE
Problem with publishing using Travis

### ISSUE THREAD

**Issue by AlexMoroz** [Rostlab/JS16_ProjectE#6]
NPM publishing doesn't work on Travis.

build output of travis, project C10:

> NPM API key format changed recently. If your deployment fails, check your API key in ~/.npmrc.
> http://docs.travis-ci.com/user/deployment/npm/
> ~/.npmrc size: 48
> npm ERR! Linux 3.13.0-40-generic
> npm ERR! argv "/home/travis/.nvm/versions/node/v5.8.0/bin/node" "/home/travis/.nvm/versions/node/v5.8.0/bin/npm" "publish"
> npm ERR! node v5.8.0
> npm ERR! npm  v3.7.3
> npm ERR! toString failed
> npm ERR! 
> npm ERR! If you need help, you may report this error at:
> npm ERR!     https://github.com/npm/npm/issues
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/travis/build/Rostlab/JS16_ProjectC_Group10/npm-debug.log

The problem is not in API key, but you can check it. 
I think the problem with nodejs version, try to google.
Manual publishing works.

**Comment by AlexMoroz** [comment]
Fixed with https://github.com/Rostlab/JS16_ProjectC_Group10/commit/c1f619884084a4e4432e78a12405e6d606818fcc

**Comment by AlexMoroz** [comment]
The package was too big for npm

**Comment by sacdallago** [comment]
:D OMG
