### ISSUE TITLE
Create npm modules for projects

### ISSUE THREAD

**Issue by AlexMoroz** [Rostlab/JS16_ProjectE#7]
https://quickleft.com/blog/creating-and-publishing-a-node-js-module/

**Comment by AlexMoroz** [comment]
Small notification:
@TheZoker @CavidSalahov @jonny3576 @AngeKouemo @Emiliyana

**Comment by sacdallago** [comment]
Can this be closed?

**Comment by jsalahov** [comment]
According to #19 Projects B6, B7, C10, D4, D5 is done. 
@TheZoker How about A and F? Should they be published to npm?

**Comment by jsalahov** [comment]
@TheZoker #5 also related. Please close both if done.

**Comment by TheZoker** [comment]
No as far as I know, nether A nor F will be published to npm, so this can be closed.
@sacdallago Can you confirm this?
