### ISSUE TITLE
Integrating double projects

### ISSUE THREAD

**Issue by jcebel** [Rostlab/JS16_ProjectE#8]
How are we gonna handle the projects B and D. There are existing two solutions for those projects.
Apparently ProjectF will only include one Project.
So we have to come up we solutions for this problem. Are there any suggestions or ideas?
Should we merge the output?

**Comment by jsalahov** [comment]
I think project F should/must show both versions. Project names are same, but implementations would be different

**Comment by gyachdav** [comment]
That's correct Project F will include both versions. How to present both versions at the same time without creating confusion on the user side is a different questions that we will resolve with F.

**Comment by sacdallago** [comment]
While as far as data goes, all of the data will be on the db serviced by **A** and hopefully there will be API calls to get the data.
